config/routes.rb
Cookbooks::Application.routes.draw do

  resources :books do 
    resources :chapters do
      resources :recipes
    end
  end


  devise_for :users

  get "home/index"

  root :to => 'home#index'

end

app/models/book.rb
class Book
  include Mongoid::Document
  field :title, type: String
  field :description, type: String

  validates_presence_of :title

  embeds_many :chapters
  belongs_to :user
end

app/models/chapter.rb
class Chapter
  include Mongoid::Document
  field :title, type: String


  validates_presence_of :title

  embedded_in :book
  embeds_many :recipes
end

app/models/recipe.rb
class Recipe
  include Mongoid::Document
  field :problem_title, type: String
  field :problem_description, type: String
  field :solution, type: String

  validates_presence_of :problem_title

  embedded_in :chapter
end

app/models/user.rb
class User
  include Mongoid::Document
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me

  ## Database authenticatable
  field :email,              :type => String, :default => ""
  field :encrypted_password, :type => String, :default => ""

  ## Recoverable
  field :reset_password_token,   :type => String
  field :reset_password_sent_at, :type => Time

  ## Rememberable
  field :remember_created_at, :type => Time

  ## Trackable
  field :sign_in_count,      :type => Integer, :default => 0
  field :current_sign_in_at, :type => Time
  field :last_sign_in_at,    :type => Time
  field :current_sign_in_ip, :type => String
  field :last_sign_in_ip,    :type => String

  ## Confirmable
  # field :confirmation_token,   :type => String
  # field :confirmed_at,         :type => Time
  # field :confirmation_sent_at, :type => Time
  # field :unconfirmed_email,    :type => String # Only if using reconfirmable

  ## Lockable
  # field :failed_attempts, :type => Integer, :default => 0 # Only if lock strategy is :failed_attempts
  # field :unlock_token,    :type => String # Only if unlock strategy is :email or :both
  # field :locked_at,       :type => Time

  ## Token authenticatable
  # field :authentication_token, :type => String

  has_many :books
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  layout :choose_layout


  def choose_layout
  	if devise_controller?
  		"devise"
  	else
  		"application"
  	end
  end

end

app/controllers/authenticated_controller.rb
class AuthenticatedController < ApplicationController
  before_filter :authenticate_user!

end

app/controllers/books_controller.rb
class BooksController < AuthenticatedController
  # GET /books
  # GET /books.json
  def index
    @books = Book.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @books }
    end
  end

  # GET /books/1
  # GET /books/1.json
  def show
    @book = Book.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @book }
    end
  end

  # GET /books/new
  # GET /books/new.json
  def new
    @book = Book.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @book }
    end
  end

  # GET /books/1/edit
  def edit
    @book = Book.find(params[:id])
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(params[:book])

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render json: @book, status: :created, location: @book }
      else
        format.html { render action: "new" }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /books/1
  # PUT /books/1.json
  def update
    @book = Book.find(params[:id])

    respond_to do |format|
      if @book.update_attributes(params[:book])
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book = Book.find(params[:id])
    @book.destroy

    respond_to do |format|
      format.html { redirect_to books_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/chapters_controller.rb
class ChaptersController < AuthenticatedController

	def create
	    @book = Book.find(params[:book_id])
	    @chapter = @book.chapters.create!(params[:chapter])
	    redirect_to @book, :notice => "Chapter created!"  
		
	end

	def show
	    @book = Book.find(params[:book_id])
	    @chapter = @book.chapters.find(params[:id])
	end
end

app/controllers/home_controller.rb
class HomeController < AuthenticatedController

  def index
  end
end

app/controllers/recipes_controller.rb
class RecipesController < AuthenticatedController
	def new
	    @book = Book.find(params[:book_id])
	    @chapter = @book.chapters.find(params[:chapter_id])
	end

	def create
	    @book = Book.find(params[:book_id])
	    @chapter = @book.chapters.find(params[:chapter_id])
	    @recipe = @chapter.recipes.create!(params[:recipe])
	    redirect_to [@book, @chapter, @recipe], :notice => "Recipe created!"  
	end

	def show
	    @book = Book.find(params[:book_id])
	    @chapter = @book.chapters.find(params[:chapter_id])
	    @recipe = @chapter.recipes.find(params[:id])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def markdown(text)  
    	Redcarpet::Markdown.new(Redcarpet::Render::HTML, :space_after_headers => true).render(text).html_safe
	end 
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/chapters_helper.rb
module ChaptersHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/books/_book_summary.html.haml
.media
  %a.pull-left{:href => "#"}
    %img.media-object{:alt => "64x64", "data-src" => "holder.js/64x64", :src => "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAYAAACqaXHeAAACeklEQVR4Xu2Y26tpURTGh7uQSB54UohEUXgQQv5swouNF7c8KEnhwV3e3E9jFO1jt0/2mmfvttaYpdWqOcec41tjfL9MxXq9voKMh4IF4ArgFmAPkLEHApsgU4ApwBRgCjAFZKwAY5AxyBhkDDIGZQwB/jPEGGQMMgYZg4xBxqCMFRDG4Hg8htFoBMfjEUwmE/j9fjCbzXdJh8Mh4A9HPp9/SurviPnZxkICzOdz6HQ6lLTRaIR2uw0WiwXC4TDtdz6foVqtwuFwgOv1+pQA3xHzX6oLCdBsNmGz2UAmkwGlUvlhn8lkAqvVChaLxb0CUIi3tzcSJJFI3EXS6/UQi8Wg1Wp9OeZTZfXJJCEBKpUKhbXb7YBfzmAwQDAYpOctUa/XS5XxvgVmsxl0u10IhUKw3W4BSz4ajVL1SI0pVQQhAYrFIiWKiVwuF+j1emCz2SASiZAg/X4fkskk4LxHD6jX6+Qb+/0eHA4HBAIBmiMSU4oIQgKUSiUq4VwuR0Lgu0qlgmw2C41GA6xWK2AFFAqFDwLcel2hUJBIOp2O5ojE/HEBMMndbkcegKNcLoNWq4V0On1P+vFQqVSKksUWQG9A4dxuN7hcLpoqEvPHBcDexTL3+XygVqupBZxO572cbwd6rIDlcklm5/F4qIIQo2iAiE+pMaUkj2uEWgADDAYDmE6n9CWx/xGJGo3mr/O8F+B0OkGtVqM58Xic1qEf4BPfUcivxpSa/H8RQGTz37BWuAJ+QxIiZ2AB+EaIb4T4RohvhERc9NXXMgWYAkwBpgBT4NWdXOT8TAGmAFOAKcAUEHHRV1/LFGAKMAWYAkyBV3dykfMzBeROgT8hMVqfwBYPNgAAAABJRU5ErkJggg==", :style => "width: 64px; height: 64px;"}/
  .media-body
    %h4.media-heading= link_to book.title, book
    .text-muted= book.description
    - if book.user_id == current_user.id
      .menu
        = link_to 'Edit', edit_book_path(book)
        |
        = link_to 'Destroy', book, :method => :delete, :data => { :confirm => 'Are you sure?' }

app/views/books/_form.html.haml
= form_for(@book, :html => {:class => 'form-horizontal', :role => 'form'}) do |f|
  - if @book.errors.any?
    .alert.alert-block.alert-danger.fade.in
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} ×
      %strong= "#{pluralize(@book.errors.count, "error")} prohibited this book from being saved:"
      - @book.errors.full_messages.each do |msg|
        %li= msg
  = f.hidden_field :user_id, :value => current_user.id 
  .form-group
    = f.label :title, :class => 'col-lg-2 control-label'
    .col-lg-10
      = f.text_field :title, :class => 'form-control'
  .form-group
    = f.label :description, :class => 'col-lg-2 control-label'
    .col-lg-10
      = f.text_area :description, :rows => 5, :class => 'form-control'
  .form-group
    .col-lg-offset-2.col-lg-10
      = f.submit 'Save' , :class => 'btn btn-primary'
      = link_to 'Cancel', books_path, :class => 'btn btn-default'

app/views/books/edit.html.haml
.page-header
  %h3 Edit book

= render 'form'

app/views/books/index.html.haml
.page-header
  %h3 Books

- @books.each do |book|
  = render 'book_summary', :book => book

%hr
= link_to 'Create a New Book', new_book_path, :class => 'btn btn-lg btn-primary'

app/views/books/new.html.haml
.page-header
  %h3 Create a new book

= render 'form'

app/views/books/show.html.haml
%p#notice= notice

.page-header
  %h2
    = @book.title
    %br
    %small= @book.description
.row
  .col-lg-8
    %h2 Chapters
    %ul
      - @book.chapters.each do |chapter|
        %li= link_to chapter.title, book_chapter_path(@book, chapter)
  .col-lg-4
    .page-header
      %h4 Add Chapter
    = form_for([@book, Chapter.new], :html => {:class => 'form-horizontal', :role => 'form'} )do |f|
      .form-group
        = f.label :title, :class => 'col-lg-2 control-label'
        .col-lg-10
          = f.text_field :title , :class => 'form-control'
      .form-group
        .col-lg-offset-2.col-lg-10
          = f.submit :class => 'btn btn-primary'



= link_to 'Edit', edit_book_path(@book)
\|
= link_to 'Back', books_path

app/views/chapters/show.html.haml
%ol.breadcrumb
  %li= link_to @book.title, book_path(@book)
  %li.active= @chapter.title

.page-header
  %h2= @chapter.title

%ul
  - @chapter.recipes.each do |recipe|
    %li= link_to recipe.problem_title, book_chapter_recipe_path(@book, @chapter, recipe)

= link_to 'Add new recipe', new_book_chapter_recipe_path(@book, @chapter), :class => 'btn btn-lg btn-primary'

app/views/home/index.html.haml
.page-header
  %h3 My Books

- current_user.books.each do |book|
  = render 'books/book_summary', :book => book

%hr
= link_to 'Create a New Book', new_book_path, :class => 'btn btn-lg btn-primary'

app/views/layouts/application.html.haml
!!!
%html{:lang => "en"}
  %head
    %meta{:charset => "utf-8"}/
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
    %meta{:content => "", :name => "description"}/
    %meta{:content => "", :name => "author"}/
    %title Cookbooks
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    .navbar.navbar-inverse.navbar-fixed-top
      .container
        .navbar-header
          %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.navbar-brand{:href => root_path } Cookbooks
        .collapse.navbar-collapse
          = render 'shared/navbar_main'
          - if user_signed_in?
            = render 'shared/navbar_aux'
    .container
      = yield

app/views/layouts/devise.html.haml
!!!
%html{:lang => "en"}
  %head
    %meta{:charset => "utf-8"}/
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
    %meta{:content => "", :name => "description"}/
    %meta{:content => "", :name => "author"}/
    %title Cookbooks
    = stylesheet_link_tag    "devise", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    .container
      = yield

app/views/recipes/_breadcrumb.html.haml
%ol.breadcrumb
  %li= link_to book.title, book_path(@book)
  %li= link_to chapter.title, book_chapter_path(@book, @chapter)
  %li.active= active

app/views/recipes/_form.html.haml
= form_for([@book, @chapter, Recipe.new], :html => {:class => 'form-horizontal', :role => 'form'} )do |f|
  .form-group
    = f.label "Title", :class => 'col-lg-2 control-label'
    .col-lg-10
      = f.text_field :problem_title , :class => 'form-control'
  .form-group
    = f.label "Problem", :class => 'col-lg-2 control-label'
    .col-lg-10
      = f.text_area :problem_description, :rows => 2, :class => 'form-control'
  .form-group
    = f.label :solution, :class => 'col-lg-2 control-label'
    .col-lg-10
      = f.text_area :solution , :rows => 14, :class => 'form-control'
  .form-group
    .col-lg-offset-2.col-lg-10
      = f.submit :class => 'btn btn-primary'

app/views/recipes/new.html.haml
= render 'breadcrumb', :book => @book, :chapter => @chapter, :active => 'New'
.page-header
  %h3 New Recipe

= render 'form'

app/views/recipes/show.html.haml
= render 'breadcrumb', :book => @book, :chapter => @chapter, :active => @recipe.problem_title

.page-header
  %h3= @recipe.problem_title

%h4 Problem
%p= @recipe.problem_description


%h4 Solution
%p= markdown(@recipe.solution)

app/views/shared/_navbar_aux.html.haml
%ul.nav.navbar-nav.navbar-right
  %li
    %a{:href => "#"} 
      %span.glyphicon.glyphicon-cog
  %li.dropdown
    %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
      %span.glyphicon.glyphicon-user
      %b.caret
    %ul.dropdown-menu
      %li
        %a{:href => "#"} Profile
      %li
        %a{:href => "#"} Manage Profile
      %li.divider
      %li= link_to('Logout', destroy_user_session_path, :method => :delete)

app/views/shared/_navbar_main.html.haml
%ul.nav.navbar-nav
  %li.active= link_to 'Books', books_path
  %li
    %a{:href => "#about"} About